server:
  port: 3000

spring:
  application:
    name: aux-test
  profiles:
    active: local

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/aux_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    data: classpath:init.sql


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
